apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nyrlc7q75-go 
  janus-idp.io/tekton: nyrlc7q75-go
  backstage.io/kubernetes-id: nyrlc7q75-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nyrlc7q75-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml