apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: nyrlc7q75-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nyrlc7q75-go 
  name: nyrlc7q75-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: nyrlc7q75-go 
